export const POST_COURSE_REQ = "POST_COURSE_REQ";
export const POST_COURSE_SUCCESS = "POST_COURSE_SUCCESS";
export const POST_COURSE_FAILURE= "POST_COURSE_FAILURE";


export const GET_COURSE_REQ = "GET_COURSE_REQ";
export const GET_COURSE_SUCCESS = "GET_COURSE_SUCCESS";
export const GET_COURSE_FAILURE= "GET_COURSE_FAILURE";